export const FORM_OPTIONS = {
  aspectRatio: [
    { value: 'n/a', label: 'N/A' },
    { value: '1:1', label: '1:1 (Quadrado)' },
    { value: '16:9', label: '16:9 (Paisagem)' },
    { value: '9:16', label: '9:16 (Retrato)' },
    { value: '4:3', label: '4:3 (TV Clássica)' },
    { value: '3:2', label: '3:2 (Fotografia)' },
    { value: '2:1', label: '2:1 (Cinematográfico)' },
  ],
  chaos: [
    { value: 'n/a', label: 'N/A' },
    { value: '0', label: '0 (Consistente)' },
    { value: '10', label: '10 (Pouco variado)' },
    { value: '25', label: '25 (Variado)' },
    { value: '50', label: '50 (Muito variado)' },
    { value: '100', label: '100 (Abstrato/Aleatório)' },
  ],
  quality: [
    { value: 'n/a', label: 'N/A' },
    { value: '.25', label: '0.25 (Rápido)' },
    { value: '.5', label: '0.5 (Meia qualidade)' },
    { value: '1', label: '1 (Padrão)' },
  ],
  style: [
    { value: 'n/a', label: 'N/A' },
    { value: 'raw', label: 'Raw' },
    { value: '4a', label: 'Estilo 4a (antigo)' },
    { value: '4b', label: 'Estilo 4b (antigo)' },
    { value: '4c', label: 'Estilo 4c (antigo)' },
    { value: 'cute', label: 'Niji-v5 Cute' },
    { value: 'expressive', label: 'Niji-v5 Expressive' },
    { value: 'scenic', label: 'Niji-v5 Scenic' },
  ],
  stylize: [
    { value: 'n/a', label: 'N/A' },
    { value: '0', label: '0 (Desligado)' },
    { value: '50', label: '50 (Baixo)' },
    { value: '100', label: '100 (Padrão)' },
    { value: '250', label: '250 (Alto)' },
    { value: '500', label: '500 (Muito Alto)' },
    { value: '1000', label: '1000 (Máximo)' },
  ],
  version: [
    { value: 'n/a', label: 'N/A' },
    { value: '6', label: 'V6 (Mais recente)' },
    { value: '5.2', label: 'V5.2' },
    { value: '5.1', label: 'V5.1' },
    { value: 'niji-v6', label: 'Niji V6 (Anime)' },
    { value: 'niji-v5', label: 'Niji V5 (Anime)' },
  ],
  camera: [
    { value: 'n/a', label: 'N/A' },
    { value: 'portrait', label: 'Retrato' },
    { value: 'wide angle shot', label: 'Lente Grande Angular' },
    { value: 'macro shot', label: 'Lente Macro' },
    { value: 'telephoto shot', label: 'Lente Teleobjetiva' },
    { value: 'drone shot', label: 'Visão de Drone' },
    { value: 'eye-level shot', label: 'Nível do Olho' },
    { value: 'low-angle shot', label: 'Ângulo Baixo' },
    { value: 'high-angle shot', label: 'Ângulo Alto' },
    { value: 'dutch angle', label: 'Ângulo Holandês' },
  ],
};

export type FormOptionKey = keyof typeof FORM_OPTIONS;
